### ISSUE TITLE
Feature: RSS Feed

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird.org#50]
Several people have reached out asking if we could create an RSS feed for posts and newsletters.

**Comment by ADKaster** [comment]
#56 adds a `posts.xml` generated from post contents.

However, it's served as `application/xml` instead of `application/rss+xml`, so the astro files probably need an update to serve it with the proper type.

**Comment by simonkrauter** [comment]
For me the web feed works! (I use FreshRSS.)
![Screenshot_2024-07-24_13-58-11](https://github.com/user-attachments/assets/39428fc4-24a1-49dc-85e0-6b930498fc0b)

**Comment by samfry13** [comment]
@ADKaster I'm not sure we can get the RSS Feed to be `application/rss+xml`. After some experimentation, it looks like if we are doing a static build generation, Astro always exports a normal `.xml` file. Which is fine, but the issue is there's no way to specify the MIME type when serving static files, at least from what I can find on GH Pages [[1](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#mime-types-on-github-pages)].

**Comment by Kingproone** [comment]
Can there be a button added to the buttons at the bottom of the page pointing to https://ladybird.org/posts.xml?
(bad mockup, ordering is up to debate)
![Screenshot_20240728_180516](https://github.com/user-attachments/assets/4c5355d5-af8b-41a9-870b-1f7679a28648)

**Comment by bbb651** [comment]
> @ADKaster I'm not sure we can get the RSS Feed to be `application/rss+xml`. After some experimentation, it looks like if we are doing a static build generation, Astro always exports a normal `.xml` file. Which is fine, but the issue is there's no way to specify the MIME type when serving static files, at least from what I can find on GH Pages [[1](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#mime-types-on-github-pages)].

The link was really helpful! Turns out it is supported, we just have to [name the file with a `.rss` extension](https://github.com/jshttp/mime-db/blob/ae4ada99c87c449c36c86fb8a08f549ee90361fb/db.json#L1560C3-L1564C5).

**Comment by jxcl** [comment]
I believe this was closed prematurely. Posts have an RSS feed, but newsletters do not appear to.
